
DROP DATABASE IF EXISTS gpx_access;
CREATE DATABASE IF NOT EXISTS gpx_access;
USE gpx_access;

CREATE TABLE IF NOT EXISTS `gpx_access`.`way_point` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longtitude` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(2048) NULL DEFAULT NULL,
  `symbol` VARCHAR(2048) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`metadata` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(2048) NULL DEFAULT NULL,
  `description` VARCHAR(4000) NULL DEFAULT NULL,
  `author` VARCHAR(2048) NULL DEFAULT NULL,
  `symbol` VARCHAR(2048) NULL DEFAULT NULL,
  `time` VARCHAR(1024) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`gpx` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `creator` VARCHAR(2048) NULL DEFAULT NULL,
  `version` VARCHAR(255) NULL DEFAULT NULL,
  `metadata_id` BIGINT(20) NULL DEFAULT NULL,
  `symbol` VARCHAR(2048) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gpx_metadata`
    FOREIGN KEY (`metadata_id`)
    REFERENCES `metadata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`track` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(2048) NULL DEFAULT NULL,
  `description` VARCHAR(4000) NULL DEFAULT NULL,
  `gpx_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_track_gpx`
    FOREIGN KEY (`gpx_id`)
    REFERENCES `gpx` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`link` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `href` VARCHAR(4000) NULL DEFAULT NULL,
  `text` VARCHAR(4000) NULL DEFAULT NULL,
  `metadata_id` BIGINT(20) NULL DEFAULT NULL,
  `track_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_link_metadata`
    FOREIGN KEY (`metadata_id`)
    REFERENCES `metadata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_track`
    FOREIGN KEY (`track_id`)
    REFERENCES `track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`segment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `track_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_segment_track`
    FOREIGN KEY (`track_id`)
    REFERENCES `track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`segment_way_point_aff` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `segment_id` BIGINT(20) NULL DEFAULT NULL,
  `way_point_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `segment_way_point_aff_segement`
    FOREIGN KEY (`segment_id`)
    REFERENCES `segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `segment_way_point_aff_way_point`
    FOREIGN KEY (`way_point_id`)
    REFERENCES `way_point` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `gpx_access`.`gpx_way_point_aff` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gpx_id` BIGINT(20) NULL DEFAULT NULL,
  `way_point_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `gpx_way_point_aff_segement`
    FOREIGN KEY (`gpx_id`)
    REFERENCES `gpx` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gpx_way_point_aff_way_point`
    FOREIGN KEY (`way_point_id`)
    REFERENCES `way_point` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;